### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by Piotrekol** [mrflashstudio/OsuParsers#22] opened 2019-09-13 20:51 UTC
Due to the amount of issues I'm about to report, I've decided to place them all there. Feel free to split them into individual issues if that's necessary.

This is the result of trying to process my whole osu songs folder with both BeatmapDecoder and StoryboardDecoder when mapset folder contained osb file.
json file with all exceptions listed below, along with exact filenames it failed with: https://puu.sh/EgQsQ.json 
 
I should also mention that I was running from source instead of nuget release.

what could be split into 15 different issues follows:
```
System.FormatException (Nieprawidłowy format ciągu wejściowego.) 
   w System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   w System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   w System.Convert.ToInt32(String value)
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 98
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/28926
https://osu.ppy.sh/beatmapsets/13038
https://osu.ppy.sh/beatmapsets/602367
https://osu.ppy.sh/beatmapsets/470977
https://osu.ppy.sh/beatmapsets/13733
https://osu.ppy.sh/beatmapsets/758227

====

```
System.IndexOutOfRangeException (Indeks wykraczał poza granice tablicy.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 99
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/4594
https://osu.ppy.sh/beatmapsets/5140
https://osu.ppy.sh/beatmapsets/6818
https://osu.ppy.sh/beatmapsets/7810
https://osu.ppy.sh/beatmapsets/5321

====

```
System.IndexOutOfRangeException (Indeks wykraczał poza granice tablicy.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 77
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/9183
https://osu.ppy.sh/beatmapsets/9251
https://osu.ppy.sh/beatmapsets/17657
https://osu.ppy.sh/beatmapsets/559622
https://osu.ppy.sh/beatmapsets/15130
https://osu.ppy.sh/beatmapsets/24685
https://osu.ppy.sh/beatmapsets/15626
https://osu.ppy.sh/beatmapsets/25700
https://osu.ppy.sh/beatmapsets/139597
https://osu.ppy.sh/beatmapsets/14648
https://osu.ppy.sh/beatmapsets/8023
https://osu.ppy.sh/beatmapsets/8010
https://osu.ppy.sh/beatmapsets/31750
https://osu.ppy.sh/beatmapsets/9779
https://osu.ppy.sh/beatmapsets/670449
https://osu.ppy.sh/beatmapsets/9040
https://osu.ppy.sh/beatmapsets/37439
https://osu.ppy.sh/beatmapsets/14032

====

```
System.NullReferenceException (Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbCommand(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 125
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 54
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 59
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/23483
https://osu.ppy.sh/beatmapsets/24417
https://osu.ppy.sh/beatmapsets/47517
https://osu.ppy.sh/beatmapsets/17154
https://osu.ppy.sh/beatmapsets/23889
https://osu.ppy.sh/beatmapsets/14576
https://osu.ppy.sh/beatmapsets/53592
https://osu.ppy.sh/beatmapsets/28255
https://osu.ppy.sh/beatmapsets/25557
https://osu.ppy.sh/beatmapsets/27043

====

```
System.IndexOutOfRangeException (Indeks wykraczał poza granice tablicy.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 99
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 59
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/5286
https://osu.ppy.sh/beatmapsets/3539
https://osu.ppy.sh/beatmapsets/7850
https://osu.ppy.sh/beatmapsets/3417
https://osu.ppy.sh/beatmapsets/1281
https://osu.ppy.sh/beatmapsets/3756
https://osu.ppy.sh/beatmapsets/5235
https://osu.ppy.sh/beatmapsets/2789

====

```
System.FormatException (Nieprawidłowy format ciągu wejściowego.) 
   w System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   w System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   w System.Convert.ToInt32(String value)
   w OsuParsers.Decoders.BeatmapDecoder.ParseHitObjects(String line) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 350
   w OsuParsers.Decoders.BeatmapDecoder.ParseLine(String line) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 108
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 55
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/46

====

```
System.IndexOutOfRangeException (Indeks wykraczał poza granice tablicy.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbCommand(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 135
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 54
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/28222
https://osu.ppy.sh/beatmapsets/37149
https://osu.ppy.sh/beatmapsets/292814

====

```
System.NullReferenceException (Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbCommand(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 125
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 54
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/33680

====

```
System.FormatException (Nieprawidłowy format ciągu wejściowego.) 
   w System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   w System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   w System.Convert.ToInt32(String value)
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 98
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 59
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/49686
https://osu.ppy.sh/beatmapsets/45250

====

```
System.IndexOutOfRangeException (Indeks wykraczał poza granice tablicy.) 
   w OsuParsers.Decoders.BeatmapDecoder.ParseLine(String line) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 84
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 55
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/50462

====

```
System.ArgumentException (Nie można znaleźć żądanej wartości '[General]'.) 
   w System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   w System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 74
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/1283
https://osu.ppy.sh/beatmapsets/3678

====

```
System.ArgumentOutOfRangeException (Wartość elementu StartIndex nie może być mniejsza od zera.) 
   w System.String.Remove(Int32 startIndex)
   w OsuParsers.Decoders.BeatmapDecoder.ParseMetadata(String line) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 194
   w OsuParsers.Decoders.BeatmapDecoder.ParseLine(String line) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 93
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 55
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/654452

====

```
System.IndexOutOfRangeException (Indeks wykraczał poza granice tablicy.) 
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbCommand(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 135
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 54
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 59
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/244929

====

```
System.NullReferenceException (Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.) 
   w OsuParsers.Decoders.BeatmapDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 65
   w OsuParsers.Decoders.BeatmapDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\BeatmapDecoder.cs:wiersz 32
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/73883

====

```
System.ArgumentException (Nie można znaleźć żądanej wartości '[[Events]'.) 
   w System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   w System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   w OsuParsers.Decoders.StoryboardDecoder.ParseSbObject(String line) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 74
   w OsuParsers.Decoders.StoryboardDecoder.Decode(IEnumerable`1 lines) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 52
   w OsuParsers.Decoders.StoryboardDecoder.Decode(String path) w D:\snip\osuParsers\OsuParsers\Decoders\StoryboardDecoder.cs:wiersz 31
   ```
Mapsets:
https://osu.ppy.sh/beatmapsets/6704

**Comment by mrflashstudio** [comment] 2019-09-14 14:09
Thank you for this HUGE issue! Everything has been fixed in recent commits. (I couldn't reproduce https://osu.ppy.sh/beatmapsets/50462 though. Open a separate issue if this is still not fixed for you.) Feel free to report any other issue you find!

**Closed as completed by mrflashstudio** 2019-09-14 14:09 UTC
